name: docya_app
description: DocYa - Login/Registro
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^6.0.0
  web_socket_channel: ^3.0.3
  ffi: ^2.1.2
  phosphor_flutter: ^2.0.1

  flutter_localizations:
    sdk: flutter

  # ðŸ”¹ Networking
  http: ^1.2.2
  dropdown_search: ^6.0.2
  url_launcher: ^6.3.0
  font_awesome_flutter: 10.5.0

  # ðŸ”” Notificaciones push
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3

  # ðŸŽ¨ Snackbars bonitos
  awesome_snackbar_content: ^0.1.3

  # ðŸ”¹ Google login & prefs
  google_sign_in: ^6.2.2
  shared_preferences: ^2.3.2

  animated_bottom_navigation_bar: ^1.3.3
  animations: ^2.0.8
  google_fonts: ^6.2.1
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  flutter_animate: ^4.5.0
  geocoding: ^2.2.2
  package_info_plus: ^8.0.0


  # ðŸ”¹ Google Maps + Places (SIN google_api_headers)
  google_maps_flutter: ^2.6.1
  google_places_flutter: ^2.0.6
  google_nav_bar: ^5.0.6

  webview_flutter: ^4.7.0
  image_picker: ^1.1.2
  flutter_local_notifications: ^17.2.1
  audioplayers: 6.4.0
  vibration: ^3.1.4

  # Deep links (Mercado Pago)
  app_links: ^6.3.2


  # ðŸ”¹ Polyline decoder
  flutter_polyline_points: ^3.1.0

  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logoblanco.png
    - assets/logo.png
    - assets/google_logo.png
    - assets/ambulancia.png
    - assets/map_style.json
    - assets/noticia1.png
    - assets/noticia2.png
    - assets/noticia3.png
    - assets/sounds/alerta.mp3
    - assets/mp_logo_blanco.png
    - assets/logonegro.png
    - assets/icons/app_icon.png



flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#14B8A6" # tu color
  adaptive_icon_foreground: "assets/icons/app_icon.png"


